modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Void%20Vanguards"
logoFile="icon.png"

[[mods]]
modId="voidvanguards"
version="1.0"
displayName="Void Vanguards"
displayURL="https://serilum.com/mod/void-vanguards"
authors="Rick South"
description='''ModJam 2025: Void Vanguards is a story-driven mod about the conflict between the Vanguard and the Voidborn.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., t128, Tyler Behl, William Innes, XAgent, ตัวตรึง พระนคร   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.voidvanguards]]
    modId="collective"
    mandatory=true
    versionRange="[8.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.voidvanguards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"
