modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Void%20Vanguards"
logoFile="icon.png"

[[mods]]
modId="voidvanguards"
version="1.2"
displayName="Void Vanguards"
displayURL="https://curseforge.com/minecraft/mc-mods/void-vanguards"
authors="Rick South"
description='''ModJam 2025: Void Vanguards is a story-driven mod about the conflict between the Vanguard and the Voidborn.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, aternosorg, Cherriesaurus, Linda Jansen, Michelle Smith, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.voidvanguards]]
    modId="collective"
    type="required"
    versionRange="[8.25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.voidvanguards]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "voidvanguards.mixins.json"